<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<div class="container main">
    <div class="col-lg-8 col-md-8 col-sm-8 main-placeholder">
        <c class="left">Pending user registrations</c>
        
    </div>
    <?php
        Index::__IncludeSidebar('admin');
    ?>
</div>