<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<div class="col-lg-4 col-md-4 col-sm-4 main-placeholder">
    <c class="left">Admin tasks</c>
    <ul style="list-style: none;margin:0px;">
        <li><?php UI::makeNavigationLink('System configuration', UI::GetPageUrl('admin-site-config'), 'admin-site-config'); ?></li>
        <li><?php UI::makeNavigationLink('Manage existing courses', UI::GetPageUrl('admin-manage-courses'), 'admin-manage-courses'); ?></li>
        <li><?php UI::makeNavigationLink('Pending user registrations', UI::GetPageUrl('admin-pending-registrations'), 'admin-pending-registrations'); ?>
        <li><?php UI::makeNavigationLink('Manage users', UI::GetPageUrl('admin-manage-users'), 'admin-manage-users');
            $mysql = new DB();
            $result = $mysql->Select(['count(*) as "PENDING_COUNT"'])
                    ->From('user')
                    ->Where('user.status=2')
                    ->Query();
            $pending_count = intval($result[0]['PENDING_COUNT']);
            if ($pending_count > 0) {
                echo ' ('.$pending_count.')';
            }
            ?>
        </li>

    </ul>
</div>
