<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<div class="col-lg-3 col-md-3 col-sm-3 main-placeholder">
    <c class="left">Panel sections</c>
    <ul style="margin:0px; padding:0px 10px;">
        <li><?php UI::makeNavigationLink('Home panel', UI::GetPageUrl('admin-home'), 'admin-home') ?></li>
        <li><?php UI::makeNavigationLink('System configuration', UI::GetPageUrl('admin-site-config'), 'admin-site-config'); ?></li>
        <li><?php UI::makeNavigationLink('Manage existing courses', UI::GetPageUrl('admin-manage-courses'), 'admin-manage-courses'); ?></li>
        <li><?php UI::makeNavigationLink('Pending user registrations', UI::GetPageUrl('admin-pending-registrations'), 'admin-pending-registrations'); ?>
        <li><?php UI::makeNavigationLink('Manage users', UI::GetPageUrl('admin-manage-users'), 'admin-manage-users');
            if ($pending_count > 0) {
                echo ' ('.$pending_count.')';
            }
            ?>
        </li>

    </ul>
</div>
