<?php
FLASH::clearFlashes();

// Initialize SYSTEM config data
$a_systemconfig = array();
$config = new CONFIG(DIR::$CONFIG . 'system.ini');
if (!$config->Exists()) {
    $config->SetHeader([
        'System general configuration',
        'DON\'T MODIFY! This is auto-generated by the system'
    ]);
    $config->Load(array(
        'enable_system' => 'true',
        'enable_registration' => 'true'
    ));
    $config->Write();
}
$a_systemconfig = $config->Read();

if (DATA::__HasPostData()) {
    
}

?>