<?php

$postSystemavailability = 'enable';
$postUserregistration = 'enable';
$postEnrollment = 'enable';
$postNewsfeed = 'enable';

// Initialize SYSTEM config data
$a_systemconfig = array();
$config = new CONFIG(DIR::$CONFIG . 'system.ini');
if (!$config->Exists()) {
    $config->SetHeader([
        'System general configuration',
        'DON\'T MODIFY! This is auto-generated by the system'
    ]);
    $config->Load(array(
        'enable_system' => 'enable',
        'enable_registration' => 'enable',
        'enable_enrollment' => 'enable',
        'enable_newsfeed' => 'enable'
    ));
    $config->Write();
} else {
    # [PREprocess] - Parse configuration data
    $configdata = parse_ini_file(DIR::$CONFIG . 'system.ini');
    $postSystemavailability = key_exists('enable_system', $configdata) ?
            $configdata['enable_system'] : 'enable';
    $postUserregistration = key_exists('enable_registration', $configdata) ?
            $configdata['enable_registration'] : 'enable';
    $postEnrollment = key_exists('enable_enrollment', $configdata) ?
            $configdata['enable_enrollment'] : 'enable';
    $postNewsfeed = key_exists('enable_newsfeed', $configdata) ?
            $configdata['enable_newsfeed'] : 'enable';
}

if (DATA::__HasPostData()) {
    echo 'Has data<br>';
    $postSystemavailability = DATA::__GetPOST('postSystemavailability', true, true, true);
    $postUserregistration = DATA::__GetPOST('postUserregistration', true, true, true);
    $postEnrollment = DATA::__GetPOST('postEnrollment', true, true, true);
    $postNewsfeed = DATA::__GetPOST('postNewsfeed', true, true, true);

    $sysconfig = new CONFIG();
    $sysconfig->Create(DIR::$CONFIG . 'system.ini');
    $sysconfig->Read();
    $sysconfig->Set('enable_system', $postSystemavailability)
            ->Set('enable_registration', $postUserregistration)
            ->Set('enable_enrollment', $postEnrollment)
            ->Set('enable_newsfeed', $postNewsfeed);
    $sysconfig->Write();
    FLASH::clearFlashes();
    FLASH::addFlash('Configuration has been successfully saved.', ['admin-site-config', 'admin-home'], 'PROMPT', true);
    UI::RedirectTo('admin-site-config');
}
?>