<html>
    <head>
        <!-- Metadata -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="A proposed system for DBMS 3CSELEC course - BS Computer Science">
        <meta name="author" content="Allen Linatoc, Imari Elanor Malabanan, Patricia Mae Marasigan">

        <!-- Bootstrap components -->
        <script type="text/javascript" src="web+/bootstrap/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="web+/bootstrap/css/bootstrap.css">

        <!-- Site components -->
        <link rel="stylesheet" href="web+/site/css/default.css">
        <link rel="stylesheet" href="web+/site/css/header.css">
        <link rel="stylesheet" href="web+/site/css/footer.css">

        <title><?php echo $HEADER_title; ?></title>
    </head>
    <body class="">
        <header class="container-fluid header">
            <div class="col-sm-4 col-md-4 col-lg-4 logo">
                <img src="web+/site/img/logo.png" class="img-responsive">
            </div>
        </header>