<html>
    <head>
        <!-- Bootstrap components -->
        <script type="text/javascript" src="web+/bootstrap/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="web+/bootstrap/css/bootstrap.css">
            
        <!-- Site components -->
        <link rel="stylesheet" href="web+/site/css/default.css">
        <link rel="stylesheet" href="web+/site/css/header.css">
        <link rel="stylesheet" href="web+/site/css/footer.css">
        
        <title><?php echo $HEADER_title; ?></title>
    </head>
    <body class="">
        <header class="container-fluid header">
            <div style="padding: 50px; background: #269abc;" class="col-lg-2">LOGO</div>
        </header>
        <div class="container main">