<html>
    <head>
        <!-- Metadata -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="A proposed system for DBMS 3CSELEC course - BS Computer Science">
        <meta name="author" content="Allen Linatoc, Imari Elanor Malabanan, Patricia Mae Marasigan">
        
        <!-- jQuery components -->
        <script type="text/javascript" src="web+/jquery/js/jquery.min.js"></script>
        <script type="text/javascript" src="web+/jquery/js/jquery-ui.min.js"></script>
        <link rel="stylesheet" href="web+/jquery/css/jquery-ui.min.css">
        <link rel="stylesheet" href="web+/jquery/css/jquery-ui.theme.min.css">

        <!-- Bootstrap components -->
        <script type="text/javascript" src="web+/bootstrap/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="web+/bootstrap/css/bootstrap.min.css">

        <!-- Site components -->
        <link rel="stylesheet" href="web+/site/css/default.min.css">
        <link rel="stylesheet" href="web+/site/css/header.min.css">
        <link rel="stylesheet" href="web+/site/css/footer.min.css">

        <title><?php echo $HEADER_title; ?></title>
    </head>
    <body class="">
        <header class="container-fluid header">
            <div class="col-sm-5 col-md-5 col-lg-5 logo">
                <img src="web+/site/img/logo.png" class="img-responsive">
            </div>
        </header>