
    <footer class="container-fluid footer container-fluid" id="footer">
        <div align="center">Astra Student System</div>
        <div align="center" style="font-size:90%">
            A proposed system by <a href="javascript:;">Allen Linatoc</a>, <a href="javascript:;">Imari Elanor Malabanan</a>, <a href="javascript:;">Patricia Mae Marasigan</a>s
            <br>
            BS Computer Science 2015
        </div>
    </footer>
</body>
</html>