
    <footer class="container-fluid footer" id="footer">
        <br>
        <br>
        <div align="left" style="font-size: 130%;">Astra Student System <?php echo date('Y'); ?></div>
        <br>
        <div align="left" style="font-size:90%">
            A proposed system by (alphabetically): <a href="javascript:;">Allen Linatoc</a>, <a href="javascript:;">Imari Elanor Malabanan</a> and <a href="javascript:;">Patricia Mae Marasigan</a>
            <br>
            BS Computer Science 2015
        </div>
        <br>
    </footer>

    <!-- Non-library scripts are loaded below for faster loading -->
    <script type="text/javascript" src="web+/site/js/"></script>
</body>
</html>