<div class="container main">
    <div class="container-fluid main-placeholder">
        <?php
        $rptActiveusers = new MYSQLREPORT(array(
            [
                'CAPTION' => 'Username'
            ],
            [
                'CAPTION' => 'First name'
            ],
            [
                'CAPTION' =>  'Last name'
            ],
            [
                'CAPTION' => 'Email'
            ]
        ));
        $rptActiveusers->setReportProperties(array(
            'width' => '100%',
            'border' => '1'
        ))->setReportCellstemplate(array(
            [], [], [], []
        ));
        
        $rptActiveusers->loadResultdata(
                ACCOUNTS::getActiveUsers(['username', 'fname', 'lname', 'email'], true)
                );
        $rptActiveusers->renderReport();
        ?>
    </div>
</div>