
<div class="container main">
    <div class="col-lg-8 col-md-8 col-sm-8 main-placeholder">
        <c class="left">Getting started</c>
        <div class="row">
            <div class="col-md-6 col-sm-6 col-xs-6 main-container">
                <c class="left mid">Sign in to your account</c>
                <form method="post" role="form">
                    <input type="text" class="form-control" placeholder="Username" required autofocus>
                    <input type="password" class="form-control" placeholder="Password">
                    <input type="submit" class="btn btn-primary btn-sm btn-block" value="Log in">
                </form>
                Don't have an account?<br>
                <a href="<?php echo UI::GetPageUrl('signup'); ?>">Request one</a>
            </div>
            <div class="col-md-6 col-sm-6 col-xs-6 main-container">
                <c class="left mid">Enroll in a course</c>
                <form method="post" role="form">
                    <input type="text" class="form-control" placeholder="Enter course code">
                    <input type="submit" class="btn btn-block btn-primary btn-sm" value="Enroll">
                </form>
            </div>
        </div>
        <br>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4 main-placeholder">
        <c class="left">Top students</c>
    </div>
</div>